[package]
name = "substrate-rpc-servers"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
jsonrpc-http-server = { git = "https://github.com/paritytech/jsonrpc.git", branch = "td-optionalmeta" }
jsonrpc-pubsub = { git = "https://github.com/paritytech/jsonrpc.git", branch = "td-optionalmeta" }
jsonrpc-ws-server = { git = "https://github.com/paritytech/jsonrpc.git", branch = "td-optionalmeta" }
log = "0.4"
serde = "1.0"
substrate-rpc = { path = "../rpc", version = "0.1" }
sr-primitives = { path = "../sr-primitives" }
